- smithy.yaml
> - feature
RM wants a Smithy file to do dependency scanning.
Add the Smithy file they suggested.
> **This library is still pre-1.0.0.**
>
> Patches and minor changes will be released in a patch version, while breaking
> changes can be released in a minor version.
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@teresarevious-wf
> REF-1356 Add a dummy smithy file

- pubspec.yaml
* [REF-1384 Cleanup and reorganization](https://github.com/Workiva/w_common/pull/5)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/0.1.0...version-bump-w_common-0-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/0.1.0...0.2.0
> CP-2876 Release w_common 0.2.0

- pubspec.yaml
* [REF-1387 Implement manageDisposer()](https://github.com/Workiva/w_common/pull/9)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/0.2.0...version-bump-w_common-1-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/0.2.0...1.0.0
> CP-2906 Release w_common 1.0.0

- smithy.yaml
- The smithy.yaml needed to be updated to include the pubspec.lock for release management purposes.
**Source:**
- Updated smithy.yaml
**Tests:**
- n/a
- passing CI's
- passing CI
@evanweible-wf
> CP-2947 Update smithy.yaml

- pubspec.yaml
* [CP-2947 Update smithy.yaml](https://github.com/Workiva/w_common/pull/11)
* [REF-1399 Fail immediately on null argument](https://github.com/Workiva/w_common/pull/14)
* [RAP-1455 Add isDisposing and isDisposedOrDisposing](https://github.com/Workiva/w_common/pull/15)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.0.0...version-bump-w_common-1-1-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.0.0...1.1.0
> CP-2939 Release w_common 1.1.0

- pubspec.yaml
* [RAP-1500 Extract manage methods into an interface](https://github.com/Workiva/w_common/pull/17)
Requested by: @bencampbell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.1.0...version-bump-w_common-1-2-0_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.1.0...1.2.0
> CP-3122 Release w_common 1.2.0

- pubspec.yaml
* [RAP-1654 Add Managed Timer Factories](https://github.com/Workiva/w_common/pull/22)
Requested by: @bencampbell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.2.0...version-bump-w_common-1-3-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.2.0...1.3.0
> WP-3218 Release w_common 1.3.0

- pubspec.yaml
* [RAP-1716 Add some additional management and helper methods](https://github.com/Workiva/w_common/pull/24)
* [RAP-1756 Remove Internal Disposable when Disposed Independently](https://github.com/Workiva/w_common/pull/25)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.3.0...version-bump-w_common-1-4-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.3.0...1.4.0
> WP-3710 Release w_common 1.4.0

- pubspec.yaml
* [RAP-1780 Handle single-subscription stream controllers better](https://github.com/Workiva/w_common/pull/28)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.4.0...version-bump-w_common-1-4-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.4.0...1.4.1
> WP-3840 Release w_common 1.4.1

- docs.yml
> - feature
We need a `docs.yml` file so that this lib's README can be displayed in the dev portal.
Added `docs.yml`
@evanweible-wf
@jayudey-wf
> WP-4012 Add a docs.yml

- pubspec.yaml
* [WP-4012 Add a docs.yml](https://github.com/Workiva/w_common/pull/30)
* [RAP-2040 Large number of managed disposables cause massive GC hit](https://github.com/Workiva/w_common/pull/32)
* [RAP-2050 Add dev tooling](https://github.com/Workiva/w_common/pull/33)
* [RAP-2067 Add event listener helpers to Disposable.](https://github.com/Workiva/w_common/pull/35)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.4.1...version-bump-w_common-1-5-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.4.1...1.5.0
> WP-3952 Release w_common 1.5.0

- pubspec.yaml
* [RAP-2111 Refactor to create VM and browser entry points.](https://github.com/Workiva/w_common/pull/37)
* [RAP-2091 Audit Stream Controller and Stream Subscription Cleanup](https://github.com/Workiva/w_common/pull/38)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.5.0...version-bump-w_common-1-6-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.5.0...1.6.0
> WP-4553 Release w_common 1.6.0

- lib/w_common.dart
Add a doc comment about the deprecated entry point.
**Docs only change!**
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp
> WP-4585 Add comment about deprecated entry point.

- pubspec.yaml
* [RAP-2125 Add leak flag functionality](https://github.com/Workiva/w_common/pull/44)
* [RAP-2147 Fix timer factory bug](https://github.com/Workiva/w_common/pull/45)
* [RAP-2068 managed stream subscriptions](https://github.com/Workiva/w_common/pull/46)
* [RAP-2157 Return ManagedDisposer from getManagedDisposer.](https://github.com/Workiva/w_common/pull/47)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.6.1...version-bump-w_common-1-7-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.6.1...1.7.0
> WP-4598 Release w_common 1.7.0

- pubspec.yaml
* [RAP-2190 Add implicit logging dependency to pubspec](https://github.com/Workiva/w_common/pull/49)
* [RAP-2201 Return Future.value()](https://github.com/Workiva/w_common/pull/50)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.7.0...version-bump-w_common-1-7-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.7.0...1.7.1
> WP-4778 Release w_common 1.7.1

- test/unit/disposable_common.dart
[Jira ticket](https://jira.atl.workiva.net/browse/RAP-2204)
The wording could be improved a little bit in tests.
Clean up wording.
@evanweible-wf
@jayudey-wf
> RAP-2204 Cleanup.

- pubspec.yaml
* [RAP-2202 Return null when appropriate.](https://github.com/Workiva/w_common/pull/52)
* [RAP-2204 Cleanup.](https://github.com/Workiva/w_common/pull/53)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.7.1...version-bump-w_common-1-7-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.7.1...1.7.2
> WP-4795 Release w_common 1.7.2

- lib/src/common/disposable.dart
> - feature
The `Disposable` recommendation was outdated.
Update it.
@evanweible-wf
@jayudey-wf
> WP-4877 Update Disposable usage recommendation

- lib/disposable.dart
- lib/disposable_browser.dart
> - feature
`DisposableManagerV6` was added but not exported.
Export `DisposableManagerV6`.
@evanweible-wf
@jayudey-wf
> WP-4904 Export DisposableManagerV6

- pubspec.yaml
* [WP-4861 Add manageAndReturnDisposable method](https://github.com/Workiva/w_common/pull/55)
* [WP-4877 Update Disposable usage recommendation](https://github.com/Workiva/w_common/pull/56)
* [WP-4904 Export DisposableManagerV6](https://github.com/Workiva/w_common/pull/58)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.7.2...version-bump-w_common-1-8-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.7.2...1.8.0
> WP-4806 Release w_common 1.8.0

- pubspec.yaml
* [RAP-2269 Un-manage managed stream subscriptions when the stream controller is closed](https://github.com/Workiva/w_common/pull/62)
* [WP-5009 Add DDC Compliance](https://github.com/Workiva/w_common/pull/63)
* [WP-5032 Accept unary and binary onError callbacks](https://github.com/Workiva/w_common/pull/64)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.8.1...Workiva:release_w_common_1_8_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.8.1...1.8.2
> WP-4945 Release w_common 1.8.2

- pubspec.yaml
* [WP-5391 Add "disposal imminent" step prior to disposal](https://github.com/Workiva/w_common/pull/66)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.8.2...Workiva:release_w_common_1_9_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.8.2...1.9.0
> WP-5038 Release w_common 1.9.0

- pubspec.yaml
* [WP-5487 Make manageAndReturnDisposable generic](https://github.com/Workiva/w_common/pull/69)
* [DOCPLAT-1447 Move cache, a few modifications](https://github.com/Workiva/w_common/pull/71)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.9.0...Workiva:release_w_common_1_10_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.9.0...1.10.0
> WP-5414 Release w_common 1.10.0

- CODEOWNERS
Add a `CODEOWNERS` file so that we can turn on the "require reviews from codeowners" option.
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
@Workiva/app-frameworks 
@Workiva/rich-app-platform-pp
> WP-5634 Add CODEOWNERS file

- lib/src/browser/disposable_browser.dart
- lib/src/common/disposable.dart
> - feature
@regenvanwalbeek-wf pointed out that we had conflicting recommendations about how to use Disposable.
Update the docs to consistently recommend the right patterns.
@evanweible-wf
@jayudey-wf
> WP-5962 Fix outdated docs

- pubspec.yaml
* [WP-5962 Fix outdated docs](https://github.com/Workiva/w_common/pull/78)
* [WP-6173 Fixes for Dart2](https://github.com/Workiva/w_common/pull/81)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.11.1...Workiva:release_w_common_1_11_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.11.1...1.11.2
> WP-5756 Release w_common 1.11.2

- analysis_options.yaml
Updating analysis options for w_common
> Update analysis options for w_common

- pubspec.yaml
* [Update analysis options for w_common](https://github.com/Workiva/w_common/pull/87)
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/w_common/pull/88)
* [MSODP-263 add applyToItem method](https://github.com/Workiva/w_common/pull/90)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.11.2...Workiva:release_w_common_1_12_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.11.2...1.12.0
> WP-6218 Release w_common 1.12.0

- pubspec.yaml
Requested by: @kerbyseeley-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.12.0...Workiva:release_w_common_1_13_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.12.0...1.13.0
> AF-297 Release w_common 1.13.0

- pubspec.yaml
* [af_new_drydock_image](https://github.com/Workiva/w_common/pull/95)
* [MSODP-839 Attach a leak flag factory to window when in debug mode](https://github.com/Workiva/w_common/pull/100)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.13.0...Workiva:release_w_common_1.14.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.13.0...1.14.0
> AF-1384 Release w_common 1.14.0

- pubspec.yaml
* [AF-1910 fixes for dart 1 and dart 2 compatibility](https://github.com/Workiva/w_common/pull/98)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.14.0...Workiva:release_w_common_1.15.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.14.0...1.15.0
> AF-2695 Release w_common 1.15.0

- lib/src/browser/disposable_browser.dart
- lib/src/common/disposable.dart
- test/unit/stubs.dart
> - feature
The debug mode is very, very noisy. We'd like to be able to choose the debug "features" we want to use in a given situation.
Add options to disable telemetry and logging (separately) in debug mode.
@evanweible-wf
@jayudey-wf
> Allow leaner debug mode

- pubspec.yaml
* [Allow leaner debug mode](https://github.com/Workiva/w_common/pull/105)
Requested by: @george.lesica
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.15.0...Workiva:release_w_common_1.15.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.15.0...1.15.1
> CPLAT-2699 Release w_common 1.15.1

- pubspec.yaml
* [Add disposable name and tidy up tooling](https://github.com/Workiva/w_common/pull/108)
Requested by: @george.lesica
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.15.1...Workiva:release_w_common_1.16.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.15.1...1.16.0
> CPLAT-4262 Release w_common 1.16.0

- pubspec.yaml
* [Add example app to see StateError](https://github.com/Workiva/w_common/pull/109)
* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/w_common/pull/112)
* [CPLAT-5075: Add name test util](https://github.com/Workiva/w_common/pull/113)
* [CPLAT-5382: Add CSS compilation pub executable](https://github.com/Workiva/w_common/pull/116)
Requested by: @corwinsheahan-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.16.0...Workiva:release_w_common_1.17.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.16.0...1.17.0
The logs for the request that created this PR can be found …
> CPLAT-4881 Release w_common 1.17.0

- pubspec.yaml
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.17.0...Workiva:release_w_common_1.18.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.17.0...1.18.0
> CPLAT-5388 Release w_common 1.18.0

- pubspec.yaml
* [CPLAT-6129: Add trailing slashes to sourceDir / outputDir](https://github.com/Workiva/w_common/pull/121)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.18.0...Workiva:release_w_common_1.18.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.18.0...1.18.1
> CPLAT-6102 Release w_common 1.18.1

- pubspec.yaml
* [CPLAT-6212: Add dedicated sass entrypoint](https://github.com/Workiva/w_common/pull/123)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.18.1...Workiva:release_w_common_1.19.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.18.1...1.19.0
> RM-53356 Release w_common 1.19.0

- pubspec.yaml
* [CPLAT-6209 Add check for compiler to use at runtime](https://github.com/Workiva/w_common/pull/124)
Requested by: @smaifullerton-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.19.0...Workiva:release_w_common_1.20.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.19.0...1.20.0
> RM-53538 Release w_common 1.20.0

- lib/src/browser/disposable_browser.dart
- lib/src/common/disposable.dart
The `LeakFlag` description is hit-or-miss, we can do better.
Use the `disposableTypeName` value along with the `runtimeType` (which doesn't work in a minified context, but that's fine).
> CPLAT-6248: Improve leakflag description

- Dockerfile
- analysis_options.yaml
- example/errors/example.dart
- lib/src/bin/compile_sass.dart
- lib/src/browser/disposable_browser.dart
- lib/src/common/cache/cache.dart
- lib/src/common/disposable.dart
- lib/src/common/disposable_manager.dart
- lib/src/common/managed_stream_subscription.dart
- test/unit/browser/cache/cache_test.dart
- test/unit/browser/cache/reference_counting_strategy_test.dart
- test/unit/browser/json_serializable_test.dart
- test/unit/browser/time_test.dart
- test/unit/disposable_common.dart
- test/unit/vm/test_utils_test.dart
We aren't using strict inference or raw types.
Go ahead and use them, because why not?
Switch on strict inference and strict raw types.
> CPLAT-6796: Add strict inference and raw types

- pubspec.yaml
* [CPLAT-6248: Improve leakflag description](https://github.com/Workiva/w_common/pull/127)
* [CPLAT-6796: Add strict inference and raw types](https://github.com/Workiva/w_common/pull/128)
* [CPLAT-6848: Add disposable type name(s)](https://github.com/Workiva/w_common/pull/129)
Requested by: @olesiathoms-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.20.0...Workiva:release_w_common_1.20.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.20.0...1.20.1
> RM-53547 Release w_common 1.20.1

- pubspec.yaml
We have consumers who are still on intl versions `^0.15.0`, but released a minor version which removes that version range.
This package can build/test with intl `^0.15.0` (see [here](https://travis-ci.org/github/Workiva/w_common/builds/694419638)), so we should allow that version as well to allow consumers to get the latest w_common versions.
[contributing-manual-testing]: https://github.com/Workiva/w_common/blob/master/CONTRIBUTING.md#manual-testing-crit …
> CPLAT-11312: Widen intl range

- pubspec.yaml
Allow Dart 2.12 users to depend on w_common (without null safety, for now)
Widen the range of intl we allow
> Widen intl range to allow Dart 2.12 dep resolution

- pubspec.yaml
Some repos at Workiva are still using version 0.11.x of logging. w_common's minimum is set to a version that 
I've widened the acceptable version range for logging so it can be consumed by other Workiva repos.
Widen version range for logging dep to `>=0.11.3+2 <2.0.0`
> Widen acceptable logging version range

- .gitignore
- run_tests.sh
- skynet.yaml
Currently the release pipeline is failing on the QA required step because there is not currently a skynet config this runs the unit tests in skynet to satisfy that requirement.
Add skynet.yaml with a config that runs the unit tests.
Add skynet config that runs the unit tests.
> FW-57 Run Unit tests in skynet

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* Minor changes:
* [Mockito 5](https://github.com/Workiva/w_common/pull/166)
* [FW-100 Switch skynet from running the unit tests to checking github workflows](https://github.com/Workiva/w_common/pull/164)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/2.0.0...Workiva:release_w_common_2.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/2.0.0...2.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=W …
> RM-149131 Release w_common 2.1.0

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* [FEA-1135: Implement `_ObservableTimer.tick`](https://github.com/Workiva/w_common/pull/168)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/2.1.0...Workiva:release_w_common_2.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/2.1.0...2.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=169)
> RM-167437 Release w_common 2.1.1

- .github/workflows/dart_ci.yml
- Dockerfile
- w_common/test/unit/browser/cache/cache_test.dart
We are moving everything to 2.18 compatibility and removing 2.13
Update CI to use 2.18.7 and stable
> Update CI to 2.18

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* [Increase the minimum sass version](https://github.com/Workiva/w_common/pull/171)
* [Update CI to 2.18](https://github.com/Workiva/w_common/pull/172)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/2.1.1...Workiva:release_w_common_2.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/2.1.1...2.1.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=173)
> RM-172950 Release w_common 2.1.2

- w_common_tools/lib/src/bin/compile_sass.dart
- w_common_tools/pubspec.yaml
This PR updates the `w_common_tools` package to null safety.
> `w_common_tools` null safety

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* Major changes:
* [Migrate to null safe](https://github.com/Workiva/w_common/pull/177)
* Minor changes:
* [`w_common_tools` null safety](https://github.com/Workiva/w_common/pull/176)
* [Pin mockito 5](https://github.com/Workiva/w_common/pull/175)
* [Use `workiva_analysis_options`; update changelog](https://github.com/Workiva/w_common/pull/178)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/2.1.2...Workiva:release_w_common_3.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/2.1.2...3.0.0
This …
> RM-181102 Release w_common 3.0.0

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* [Rollout Analyzer 5](https://github.com/Workiva/w_common/pull/184)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/3.0.0...Workiva:release_w_common_3.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/3.0.0...3.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=185)
> RM-187771 Release w_common 3.0.1

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* [Dart 2.19](https://github.com/Workiva/w_common/pull/187)
* [FEDX-696 : GHA OSS changes to w_common](https://github.com/Workiva/w_common/pull/188)
* [Replace mockito with mocktail](https://github.com/Workiva/w_common/pull/189)
* [Address lint by switching to whenComplete](https://github.com/Workiva/w_common/pull/190)
Requested by: @tomconnell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/3.0.1...Workiva:release_w_common_3.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/3.0.1...3.0.2
This pull request can be …
> RM-214546 Release w_common 3.0.2

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
Requested by: @tomconnell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/3.1.0...Workiva:release_w_common_3.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/3.1.0...3.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=192)
> RM-271463 Release w_common 3.1.1

- .github/workflows/dart_ci.yml
- w_common/CHANGELOG.md
- w_common/analysis_options.yaml
- w_common/lib/json_serializable.dart
- w_common/lib/src/common/disposable.dart
- w_common/lib/src/common/managed_stream_subscription.dart
- w_common/pubspec.yaml
- w_common_tools/lib/src/bin/compile_sass.dart
We want to be consistent with the types of maps when handling json. These common types can be defined as typedefs and reused everywhere.
- Adds JsonMap and JsonMapObject typedefs
- Update SDK minimum to 2.19.0 to support the non-function
typedef language feature.
- Raised package versions to their first nullsafe version.
> Add typedefs for json maps

- w_common/pubspec.yaml
- w_common_tools/pubspec.yaml
* Minor changes:
* [Add typedefs for json maps](https://github.com/Workiva/w_common/pull/194)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/3.1.1...Workiva:release_w_common_3.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/3.1.1...3.2.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/6594079455444992/?repo_name=Workiva%2Fw_common&pull_number=195)
> RM-271471 Release w_common 3.2.0

- w_common/CHANGELOG.md
- w_common/lib/src/browser/disposable_browser.dart
- w_common/lib/src/common/disposable.dart
- w_common/lib/src/common/disposable_manager.dart
- w_common/test/unit/disposable_common.dart
> Revert "FEDX-1991: allow a nullable to be managed"
