pubspec.yaml

- [CP-2741 Add new Func<T> generic typedef](https://github.com/Workiva/w_common/pull/4)
- [cp-2743 : added JsonSerializable + test](https://github.com/Workiva/w_common/pull/5)
- [CP-2777 Add invalidation_mixin](https://github.com/Workiva/w_common/pull/6)
- [REF-1340: Prep for OSS](https://github.com/Workiva/w_common/pull/7)
- [REF-1341 Fix warnings, tidy tests, fix doc comments.](https://github.com/Workiva/w_common/pull/2)
- [REF-1356 Add a dummy smithy file](https://github.com/Workiva/w_common/pull/3)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/0.0.1...version-bump-w_common-0-0-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/0.0.1...0.0.2

CP-2625 Release w_common 0.1.0

---

lib/disposable.dart
test/unit/vm/disposable_test.dart
tool/dev.dart

**NOTE:** I'm recreating this so that the RM tooling can tell it apart from the PRs to the old repo.
It would be nice for Disposable to be able to automagically manage arbitrary objects the way it can manage stream subscriptions and other `Disposable` things.
Add a `manageDisposer` method (I'm open to renaming) that will accept a callback that is expected to handle cleanup of one or more objects (usually one, I would imagine).
> **This library is still pre-1.0.0.**
>
> Patches and minor changes will be released in a patch version, while breaking
> changes can be released in a minor version.
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf @ref-pp

REF-1387 Implement manageDisposer()

---

lib/disposable.dart
test/unit/vm/disposable_test.dart

Right now we fail if one of the "manage" methods on `Disposable` gets a `null` value. However, we only fail once `dispose()` has been called, so the error is rather confusing.
It seems reasonable to me that those methods shouldn't accept `null` arguments because there's no reason for that to ever occur in actual code, and if it did, it's almost certainly a bug in the consumer's code. If we don't deal with the `null` noisily it could lead to tricky memory leaks or other hard-to-find errors.
However, we should fail immediately so that we provide the consumer with an easily-understood stack trace and error message. This PR just makes those methods throw if they get a `null` argument.
> **This library is still pre-1.0.0.**
>
> Patches and minor changes will be released in a patch version, …

REF-1399 Fail immediately on null argument

---

.github/PULL_REQUEST_TEMPLATE.md
lib/disposable.dart
test/unit/vm/disposable_test.dart

It would be handy for consumers to have two getters available to them:
* `isDisposing` - we already had this internally. It is useful because once `dispose()` is called all bets are off as far as using stream controllers and other "managed" objects. But right now there's no way for consumers to guard their code to prevent, for example, adding to a closed stream controller.
* `isDisposedOrDisposing` - this is just a convenient shortcut for `object.isDisposed || object.isDisposing` (shocking, I know). In most cases consumers would want to use this check to guard stream controllers, etc.
Add the above getters and make sure they're exercised in the tests.
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf

RAP-1455 Add isDisposing and isDisposedOrDisposing

---

lib/disposable.dart

We want to be able to expose the helpful manage methods without making a class itself "Disposable".
Extract manage methods into an interface that we then implement in `Disposable`. Additionally, remove `@protected` from the manage method implementations. We need this for two reasons. First, because they're not technically part of the interface if they're protected, and second, because we want to be able to use `Disposable` as a concrete proxy. Finally, make `Disposable` concrete.
@evanweible-wf
@jayudey-wf
@bencampbell-wf 
@aaronstgeorge-wf

RAP-1500 Extract manage methods into an interface

---

lib/json_serializable.dart
test/unit/vm/generated_vm_tests.dart
test/unit/vm/json_serializable_test.dart

Adds a `toJsonString()` method to `JsonSerializable` to reduce legwork of consumers working with actual JSON strings. Prevents the needs for consumers to import `dart:convert` and wrap the object in `JSON.encode()` calls.
As I'm making this PR I'm realizing there may be objections to this as it prevents use from being able to easily use this as an interface (via `implements`) and instead works better with `extends` or `with`. If everyone objects, we can close this, but I thought I'd at least put it up for debate/posterity.
@Workiva/web-platform-pp 
@Workiva/rich-app-platform-pp

Add toJsonString() method to JsonSerializable

---

analysis_options.yaml
lib/src/disposable/disposable.dart
lib/src/disposable/disposable_manager.dart
pubspec.yaml
test/unit/stubs.dart
test/unit/vm/disposable_test.dart

Based on some of our discussions around memory leaks and best practices I decided to add a few more, hopefully helpful utility methods.
Add the following:
* `Future<T> awaitBeforeDispose<T>(Future<T> future)` - causes the object to await the given future before disposing. The future itself is returned for convenience.
* `Future<T> getManagedDelayedFuture<T>(Duration duration, T callback())` - returns a delayed future that will complete with the result of calling `callback` after a specific duration. If the object is disposed before the duration has elapsed the future will still complete, but with an `ObjectDisposedException` error.
* `Completer<T> manageCompleter<T>(Completer<T> completer)` - manages a completer by completing it with an `ObjectDisposedException` error if the object is …

RAP-1716 Add some additional management and helper methods

---

lib/src/disposable/disposable.dart
test/unit/vm/disposable_test.dart

There are two situations in which managing a single-subscription stream controller will result in an exception on dispose.
1. The stream has already been closed
2. The stream had a listener and that listener was subsequently canceled *before* disposal occurred
Use some hackery to figure out if the stream was listened-to and the listener subsequently canceled its subscription. Also, check to see if the stream was already closed before we try to listen to it again.
As an aside, the reason we listen to the stream before closing the controller is that closing a controller that has never had a listener will cause an exception to be thrown.
We probably want @dustinlessard-wf and / or @bencampbell-wf to give this a glance to make sure I haven't introduced any new memory leaks. …

RAP-1780 Handle single-subscription stream controllers better

---

lib/src/disposable/disposable.dart
lib/src/disposable/disposable_manager.dart

> - feature
When there are a large number of managed disposables (10k+), disposal of the managing object causes a large number of garbage collections apparently due to the list of futures that we build in the dispose() method.
This isn't a perfect solution (yet) but I think it improves things a bit. We don't build a list of futures. Instead we await them one at a time in a for-loop.
This would perform much better if we didn't have to check to `isDisposedOrDisposing` in the callbacks we set up on management. However, these are necessary, for now, because the documented semantics allow most managed objects to be disposed / closed out-of-band. This means we have to handle that …

RAP-2040 Large number of managed disposables cause massive GC hit

---

example/disposable/example.dart
example/disposable/index.html
example/index.html
lib/src/disposable/disposable.dart
test/unit/vm/disposable_test.dart
tool/dev.dart

We'd like to add some dev tooling to help with debugging and optimization going forward.
* Add a getter (`disposalTreeSize`) to count the number of nodes in a given disposal tree to aid in performance testing / debugging
* Add a "debug mode" that does some pretty verbose logging when enabled to allow the lifecycle of disposables to be tracked
@evanweible-wf
@jayudey-wf

RAP-2050 Add dev tooling

---

example/disposable/example.dart
tool/dev.dart

I've audited the usage of stream controllers and stream subscriptions in w_common and determined they are all cleaned up correctly.
However, in doing this I took some heap snapshots in the disposable example and found it a little less than straightforward to determine if everything created in the example was cleaned up properly.
Created a `TreeNode` class used to build the tree of disposables in the example. This allows you to search for `TreeNode` in the heap snapshots in Chrome and determine if the tree was cleaned up completely.
@Workiva/web-platform-pp 
@Workiva/rich-app-platform-pp

RAP-2091 Audit Stream Controller and Stream Subscription Cleanup

---

pubspec.yaml

* [WP-4585 Add comment about deprecated entry point.](https://github.com/Workiva/w_common/pull/41)
* [RAP-2123 Enable mixing in browser version of Disposable](https://github.com/Workiva/w_common/pull/42)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.6.0...version-bump-w_common-1-6-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.6.0...1.6.1

WP-4583 Release w_common 1.6.1

---

lib/src/browser/disposable_browser.dart
lib/src/common/disposable.dart
lib/src/common/disposable_manager.dart
test/unit/disposable_common.dart

@greglittlefield-wf suggested that if we annotated disposable objects with instances of a special class upon disposal, we would be better able to find things that were being leaked by searching for the special class in a heap snapshot. In theory, any instance that shows up is a leak (assuming the GC has run).
Here's Greg's example https://gist.github.com/greglittlefield-wf/4703ff40c98800047e279ca73df715b7
Add a `LeakFlag` and corresponding attribute to `Disposable`.
@evanweible-wf
@jayudey-wf

RAP-2125 Add leak flag functionality

---

lib/src/common/disposable.dart
test/unit/disposable_common.dart

We allow the managed timer factories to be called during / after disposal but this will often (or perhaps always) result in a rather obscure exception because we attempt to add to the `_internalDisposables` list while it is being iterated.
A quick fix would have been to simply copy the list before iterating, but this could have actually resulted in memory leaks, particularly in the case of periodic timers since a new timer would have been created and then never forcibly disposed.
A better fix is to simply throw if one of those factories is called during / after disposal. This is the pattern we follow for the other management methods.
Throw if one of the managed timer factories is invoked during or after disposal.
@evanweible-wf
@jayudey-wf …

RAP-2147 Fix timer factory bug

---

lib/disposable.dart
lib/disposable_browser.dart
lib/src/browser/disposable_browser.dart
lib/src/common/disposable.dart
lib/src/common/disposable_manager.dart
smithy.yaml
test/unit/disposable_common.dart

[Jira Ticket](https://jira.atl.workiva.net/browse/RAP-2157)
Problem
--------
Currently there is no way for `Disposable` to know if a `Disposer` has been short circuited, e.g. called before disposal of the object. References held in redundant disposers have been a vector for leaks in the past.
Solution
--------
If `manageDisposer` instead returned a `Disposable` that could be called by consumers when they intended the disposers functionality to be invoked, `Disposable` would know when a `Disposer` has become redundant and could therefore be removed from internal collections. To this end `SimpleDisposable` was created and a new method `getManagedDisposer`. `manageDisposer` was deprecated.
Tests
--------
Added tests for new functionality.
@evanweible-wf
@jayudey-wf …

RAP-2157 Return ManagedDisposer from getManagedDisposer.

---

.travis.yml
pubspec.yaml

The CI script was added to perform a publish dry run. This will ensure
CI fails if any warnings are generated by the validation process.
A implicit dependency on the `logging` package was introduced.
An explicit dependency on the logging package was introduced. The CI process includes performing a dry run of the publish command which validates the package. If any new implicit dependencies are introduced it will fail the CI.
@evanweible-wf
@jayudey-wf

RAP-2190 Add implicit logging dependency to pubspec

---

lib/src/common/disposable.dart
lib/src/common/disposable_manager.dart
test/unit/disposable_common.dart

[Jira ticket](https://jira.atl.workiva.net/browse/RAP-2201)
`Future.value()` returns a future that is guaranteed to complete on the next event loop cycle, whereas `new Future((){})` enqueues a new future. In 1.7.0 we started returning a new enqueued future rather than a Future guaranteed to complete on the next event loop iteration. We should keep the API consistent.
Revert to returning `Future.value()`.
@evanweible-wf
@jayudey-wf

RAP-2201 Return Future.value()

---

lib/src/common/disposable.dart
lib/src/common/managed_stream_subscription.dart
test/unit/disposable_common.dart
test/unit/stubs.dart

[Jira ticket](https://jira.atl.workiva.net/browse/RAP-2202)
`StreamSubscription.cancel()`, "Returns a future that is completed once the stream has finished its cleanup" in other words a synchronous future. StreamSubscription.cancel(), also, "For historical reasons, may ... return null if no cleanup was necessary." w_common currently returns a new enqueued asynchronous future if the cancel call returns null. This is incorrect and should be fixed.
Return null when appropriate.
@evanweible-wf
@jayudey-wf
@bencampbell-wf 
@georgelesica-wf 
@todbachman-wf 
@smaifullerton-wk

RAP-2202 Return null when appropriate.

---

lib/src/browser/disposable_browser.dart
lib/src/common/disposable.dart
lib/src/common/disposable_manager.dart
test/unit/disposable_common.dart
test/unit/stubs.dart

Injecting dependencies into an object through named parameters has become a common, useful pattern as it allows the ability to specify these dependencies only if necessary and have a fallback that is constructed for you. 
In the case of disposables, the recommended pattern is to manage the disposable _only if_ the object creates a new instance. If a disposable gets passed into the object, the object should not manage the disposable as its lifetime might last longer. In order to accomplish this, the object must check if a dependency was passed in, and if not create one and manage it. There are several ways to accomplish this, but all involve conditional uses of `manageDisposable()` which start to add up as more dependencies are allowed: 
```dart
class MyDisposable extends Disposable {
// …
```

WP-4861 Add manageAndReturnDisposable method

---

lib/src/common/disposable.dart
test/unit/disposable_common.dart

> - feature
XBRL reported a bug where canceling a managed timer within the timer's callback would throw. While this isn't strictly necessary as far as anyone knows, the Dart built-in timers support it, so we should as well.
See: https://github.com/Workiva/xbrl-module/pull/512/files#diff-875ec1f8d234f5969b7ff1935ddb1cf0R59
Check the relevant future before completing it.
I also took the opportunity to update some documentation.
@evanweible-wf
@jayudey-wf
@danaoredson-wf

RAP-2264 Allow managed timers to be canceled inside their callbacks

---

.travis.yml
pubspec.yaml

* [RAP-2264 Allow managed timers to be canceled inside their callbacks](https://github.com/Workiva/w_common/pull/60)
Requested by: @georgelesica-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.8.0...version-bump-w_common-1-8-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.8.0...1.8.1

WP-4908 Release w_common 1.8.1

---

example/disposable/example.dart
lib/src/browser/disposable_browser.dart
pubspec.yaml
smithy.yaml
test/unit/disposable_common.dart

w_common fails when running ddc tests
Updated tests to ensure ddc compliance
Updated Smithy to run ddc tests during CI
Bonus: addressed analyzer hints
@evanweible-wf
@jayudey-wf

WP-5009 Add DDC Compliance

---

lib/src/common/disposable.dart
lib/src/common/managed_stream_subscription.dart
test/unit/disposable_common.dart

> - feature
Managed subscriptions create through `listenToStream` do not un-manage when the corresponding stream controller is closed. We can achieve this using the `onDone`.
Mimic the behavior of built-in stream subscriptions using `onDone`. Also, since the same thing should happen when the stream delivers an error if `cancelOnError` was true, implement this behavior as well.
@evanweible-wf
@jayudey-wf

RAP-2269 Un-manage managed stream subscriptions when the stream controller is closed

---

lib/src/common/managed_stream_subscription.dart
test/unit/disposable_common.dart

The `ManagedStreamSubscription` class expected a binary onError callback of type `void onError(error, [stackTrace]);`, but `Stream.listen()` accepts both unary and binary onError callbacks. Passing a unary onError callback to `listenToStream` currently results in an error like so:
```
type '([Object]) => dynamic' is not a subtype of type '(dynamic, [dynamic]) => void' of 'handleError'
```
You can see this by checking out the failed tests from the first commit's build:
https://ci.webfilings.com/build/997261
To fix this, we can take the same approach as the `dart:async` implementation of `StreamSubscription` – typing `onError` as `Function` and then checking to see whether it is unary or binary and then calling it with the appropriate arguments.
_From dart:async/stream_impl.dart …

WP-5032 Accept unary and binary onError callbacks

---

lib/src/browser/disposable_browser.dart
lib/src/common/disposable.dart
lib/src/common/disposable_manager.dart
lib/src/common/disposable_state.dart
pubspec.yaml
test/unit/disposable_common.dart
test/unit/stubs.dart

There are 2 issues being addressed here:
1. The existing logic around awaitable futures (futures registered via `awaitBeforeDispose`) only waits for the set of futures available when `dispose()` is called – but ignores additional futures registered between calling `dispose()` and when all other awaitable futures have completed.
1. Currently, `isDisposing=true` as soon as `dispose()` is called. However, actual disposal doesn't begin until after the awaitable futures complete. This means that the `Disposable` API is unusable sooner than it needs to be because they check for `isDisposingOrDisposed`.
- Use a `while` loop to continuously wait for registered futures until there are no more.
- Switch to an internal enum to manage the state of the Disposable instance
- Add a `Future<Null> …

WP-5391 Add "disposal imminent" step prior to disposal

---

lib/disposable.dart
lib/disposable_browser.dart
lib/src/browser/disposable_browser.dart
lib/src/common/disposable.dart
lib/src/common/disposable_manager.dart
lib/src/common/managed_stream_subscription.dart
test/unit/disposable_common.dart

The `manageAndReturnDisposable` function should have been generic so that its return value was useful as the same type as its argument. For example, it should be type-safe to do the following:
```dart
MyThing thing = new MyThing();
thing = manageAndReturnDisposable(thing);
```
Add a method `manageAndReturnDisposable<T extends Disposable>(T disposable);`.
@evanweible-wf
@jayudey-wf

WP-5487 Make manageAndReturnDisposable generic

---

pubspec.yaml

* [DOCPLAT-1525 Create least recently used caching strategy](https://github.com/Workiva/w_common/pull/74)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.10.0...Workiva:release_w_common_1_11_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.10.0...1.11.0

WP-5655 Release w_common 1.11.0

---

lib/src/common/disposable.dart

Rename loggers to follow the pattern: `<package_name>.<class_name>` per @leerobinson-wf's email to wf-dev.
@Workiva/app-frameworks

WP-5742 w_common should follow new logger name standard

---

pubspec.yaml

* [WP-5634 Add CODEOWNERS file](https://github.com/Workiva/w_common/pull/70)
* [WP-5742 w_common should follow new logger name standard](https://github.com/Workiva/w_common/pull/76)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/1.11.0...Workiva:release_w_common_1_11_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/1.11.0...1.11.1

WP-5668 Release w_common 1.11.1

---

.gitignore
.travis.yml
lib/src/common/disposable.dart

- There's a missing implementation of the `tick` method for `_ObservableTimer`. 
```
w_common git:(master) ✗ dda
::: dartanalyzer --fatal-warnings --strong lib/disposable.dart lib/invalidation_mixin.dart lib/cache.dart lib/disposable_browser.dart lib/func.dart lib/json_serializable.dart lib/w_common.dart test/unit/typedefs.dart test/unit/stubs.dart test/unit/disposable_common.dart tool/dev.dart
Analyzing lib/disposable.dart, lib/invalidation_mixin.dart, lib/cache.dart, lib/disposable_browser.dart, lib/func.dart, lib/json_serializable.dart, lib/w_common.dart, test/unit/typedefs.dart, test/unit/stubs.dart, test/unit/disposable_common.dart, tool/dev.dart...
error • Missing concrete implementation of getter 'Timer.tick' at lib/src/common/disposable.dart:83:7 • …
```

WP-6173 Fixes for Dart2

---

.travis.yml
lib/src/common/cache/cache.dart
test/unit/browser/cache/cache_test.dart

Working with consumption in `internal application X` recently has shown that it would be a helpful for the cache to have a get that works like a map get rather than a cache get. In other words the caching strategy would not be informed of the get and it would not count towards against the removal of the item being referenced from the cache. This can be very useful when one wants to mutate an item that is known to be in the cache.
Added a method to the cache that will run a callback on an item in the cache without doing a get. As a bonus it will ensure that the events will not be put on the `didRemove` stream until the callback has finished running. To guard against the situation where a consumer chooses to dispose on removal of an object from the cache and applies a long running callback …

MSODP-263 add applyToItem method

---

.travis.yml
lib/src/browser/disposable_browser.dart
lib/src/common/disposable.dart
tool/format.sh
tool/test.sh

> - feature
It might be useful for consumers to be able to see which class has thrown a given exception while debugging.
Add an optional "name" field to `Disposable` to help with debugging.
@evanweible-wf
@jayudey-wf

Add disposable name and tidy up tooling

---

example/errors/example.dart
lib/test_utils.dart
test/unit/vm/test_utils_test.dart

@joshprzybyszewski-wf implemented `disposableTypeName` for several of our projects and it was suggested that it might be nice to unit test that the names match the class names. This seemed like something that could be provided as a test utility here.
Add `verifyDisposableTypeName` as a test utility (using a new entry point).
Add a test utility to assist in asserting that implementations of `disposableTypeName` are, and remain, correct.
As long as CI passes we should be fine here.
Please review: @joshprzybyszewski-wf 
[contributing-review-types]: …

CPLAT-5075: Add name test util

---

README.md
bin/compile_sass.dart
lib/src/bin/compile_sass.dart
pubspec.yaml
test/unit/vm/compile_sass_test.dart
test/unit/vm/fixtures/sass/nested_directory/nested_test.scss

The new [`compile_sass`](https://github.com/Workiva/w_common/pull/116) script does not have an option to run it as a watcher that recompiles sass files on every change.
1. Added a `--watch` flag
2. Improved output of `--help`
3. Added a utility class to make passing around common CLI options to multiple functions less verbose
4. Added color to the output of the script
5. Compressed output file extensions can now be customized when more than one `outputStyle` is set, as long as it doesn't match the extension used for the file extension used for the "expanded" one.
Add --watch option to compile_sass script
Please review: @greglittlefield-wf @corwinsheahan-wf …

CPLAT-5536: Add --watch option to compile_sass script

---

lib/src/bin/compile_sass.dart
test/unit/vm/compile_sass_test.dart

#119 introduced a regression for consumers that were not providing a trailing slash when specifying `--sourceDir` or `--outputDir` arguments.
1. Tack on a trailing slash in the constructor for either argument if one was not provided to ensure accurate "sub directory" inference later on.
2. Add tests.
Fix an issue with the compile_sass script that caused it to fail when no trailing slash was present on the `--sourceDir` or `--outputDir` arguments. …

Add trailing slashes to sourceDir / outputDir

---

lib/sass.dart
lib/src/bin/compile_sass.dart

Exposes some constants / entrypoints needed for https://github.com/Workiva/dart_dev/pull/305

CPLAT-6212: Add dedicated sass entrypoint

---

example/disposable/example.dart
lib/src/browser/disposable_browser.dart
lib/src/common/cache/cache.dart
pubspec.yaml
test/unit/browser/browser_stubs.dart
test/unit/stubs.dart
test/unit/vm/test_utils_test.dart
test/unit/vm/vm_stubs.dart

Some of the classes that extend or mixin `Disposable` missing `disposableTypeName` override.
This PR will add missing overrides, where it's necessary

CPLAT-6848: Add disposable type name(s)

---

docs.yml

https://jira.atl.workiva.net/browse/DE-552
As part of, 
[Dev Portal Service deprecation](https://wiki.atl.workiva.net/display/DE/Poster+-+Dev+Portal+Discovery+2.0%3A+Discovery+and+Planning); 
we are deprecating the “docs.yml” file that’s been created to render repo markdown files on to the portal.
File paths included in docs.yml of this repo will no longer be rendered/hosted on
[Dev Portal](https://dev.workiva.net/docs/) with the yml file deletion.
Please reach out to `#support-dev-portal` or `#support-developer-efficiency` with any questions.
[_Created by Sourcegraph batch change `Workiva/remove_docs_yml`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/remove_docs_yml)

DE-679: Delete docs.yml file created for Dev Portal.

---

lib/disposable.dart
lib/disposable_browser.dart

Currently consumers of disposable.dart are reaching into `src` to grab the `LeakFlag` class. This is not advisable.
Show `LeakFlag` class on export of disposable.dart 

Export LeakFlag class

---

pubspec.yaml

The 0.16.0 release of intl has been code reviewed, and no breakages are expected - only very minor typing updates were applied to some function parameters, and these parameters likely would already have the correct type in order for it to function properly now. We will double-check the app on 0.16.x once all packages allow it in their range.
Please merge once CI passes. For questions, reach out to #support-esg on Slack.
Thank you!
[_Created by Sourcegraph batch change `Workiva/upgrade_intl_allow_16`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/upgrade_intl_allow_16)

Adjust the dependency range of intl to allow 0.16.x

---

w_common/CHANGELOG.md
w_common/lib/src/common/disposable.dart

This was originally unimplemented because it was added to the `Timer` interface in Dart 2 and so there was no way to implement it in Dart 1. Now that this package requires Dart 2, we can safely implement it.

FEA-1135: Implement `_ObservableTimer.tick`

---

.github/workflows/dart_ci.yml
w_common/pubspec.yaml
w_common_tools/pubspec.yaml

This batch will raise the minimum of workiva_dependency_constrainer
to one that requires analyzer 5, thus ensuring that a repo resolves
to analyzer 5. It also raises the minimums of other packages that
are needed, like built_value.
1. Probably the most common thing is that built_value generated code
will need to be regenerated. There should be no breaking changes in
this new generated code. Some repos have a make target called `gen`,
`gen-built` or similar, or just run a full `dart run build_runner build`
2. The temporary fix for Dart coverage needs to be removed. The fix
is to simply remove lines like these below from Github Actions. This PR
will have raised the minimum of the test package to 1.21.1 which is
the first version needed that removes the need to backpatched test
versions.
``` …
```

Rollout Analyzer 5

---

w_common/pubspec.yaml
w_common_tools/pubspec.yaml

This PR raises the max version of build_web_compilers to 5.0.0 to prep for Dart 3. 
Since we're all on Dart 2.19 right now, no pub resolution will change as we can't
actually resolve to build_web_compilers 4+ without Dart 3.
Passing CI should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `$support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/build_web_compilers_raise_max_v5_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/build_web_compilers_raise_max_v5_0_0)

Raise the build_web_compilers dependency max to v5.0.0

---

w_common/pubspec.yaml

This PR raises the min version of meta to 1.16.0. Passing CI
should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `#support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/meta_raise_min_v1_16_0_really`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/meta_raise_min_v1_16_0_really)

Raise the meta dependency min to v1.16.0

---

w_common/CHANGELOG.md
w_common/lib/src/browser/disposable_browser.dart
w_common/lib/src/common/disposable.dart
w_common/lib/src/common/disposable_manager.dart
w_common/test/unit/disposable_common.dart

When migrating disposables to null safety, it would be helpful to be able to manage a **nullable** disposable. For example:
```
LoggingDataService? logging;
...
void _cloneBaseDataServices(AppIntelligence other) {
manageDisposable(logging);
}
```
Alternatively,
```
LoggingDataService? logging;
...
void _cloneBaseDataServices(AppIntelligence other) {
logging = manageAndReturnTypedDisposable(other.logging?.clone(_appName));
}
```
In fact, when we inspect the `manageDisposable` [implementation](https://github.com/Workiva/w_common/blob/master/w_common/lib/src/common/disposable.dart#L557 ), we see that we have already accommodated the incoming value being null, despite our nullable-typing suggesting it cannot be.  I believe this was an oversight.
Additionally, the …

FEDX-1991: allow a nullable to be managed

---

w_common/pubspec.yaml
w_common_tools/pubspec.yaml

* Minor changes:
* [FEDX-1991: allow a nullable to be managed](https://github.com/Workiva/w_common/pull/198)
* [Raise the build_web_compilers dependency max to v5.0.0](https://github.com/Workiva/w_common/pull/196)
* [Raise the meta dependency min to v1.16.0](https://github.com/Workiva/w_common/pull/197)
Requested by: @dustin.pauze
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_common/compare/3.2.0...Workiva:release_w_common_3.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_common/compare/3.2.0...3.3.0
This pull request can be recreated by clicking …

RM-289060 Release w_common 3.3.0

---

w_common/dart_dependency_validator.yaml
w_common/pubspec.yaml
w_common_tools/dart_dependency_validator.yaml
w_common_tools/pubspec.yaml

Updates the pubspec.yaml configuration of dependency_validator to use the updated dart_dependency_validator configuration
For any questions, please reach out to #support-frontend-dx
[_Created by Sourcegraph batch change `Workiva/dart_dependency_validator_config`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/dart_dependency_validator_config)

dart_dependency_validator_config
